#!/bin/env bash
# We kill existent nimlsp's because if NeoVim is running
# they will be restarted. If not it automatically save resources
pkill -9 nimlsp

while : ; do
    [[ ! -d "/proc/${PPID}" ]] && exit
    nimlsp --stdin --refresh <&0
    sleep 2
done
